### ISSUE TITLE
코드 컨벤션

### ISSUE THREAD

**Issue by f-lab-bright** [f-lab-edu/FoodEats#11]
@Maestro6788 @yusok7 
코드 컨벤션에 대해서 한 번 정리 하고 넘어가보면 좋을 것 같네요.

변수 선언 시 kebab, snake, camel, pascal case 등을 하나로 정합니다.
특정 타입의 경우 위 case를 무시할 수도 있습니다 (static final 변수, constants로 사용되는 상수).

인덴트의 형식을 정합니다 (tab or space).

if, for 등의 블럭 시작 코드에 줄바꿈을 할지 말지 정합니다.

위 컨벤션을 커밋 전에 검증할 수 있는 방법을 찾아봅니다.

**Comment by yusok7** [comment]
좋은 지적 감사합니다!
멘토님께서 지적해주시고 저희끼리 공부하며 코드 컨벤션에 대해 알아가는 좋은 시간을 가졌습니다.

다만 생각보다 내용이 방대하고 지켜야 할 규칙이 많은 것 같아, 저희가 작성한 코드에 완전히 반영하여 진행은 못한것 같습니다.

현재 저희가 필터, 인터셉터를 활용하여 로그인된 사용자를 인증하는 부분까지 코드를 구현해 놓은 상황입니다.
이전 내용부터 현재 진행상황까지 코드 컨벤션을 준수하였는지 확인 후 PR하도록 하겠습니다!
