### ISSUE TITLE
세션 Attribute는 식별자의 역할을 할 수 있는지?

### ISSUE THREAD

**Issue by Maestro6788** [f-lab-edu/FoodEats#14]
![image](https://user-images.githubusercontent.com/83272619/124369974-d589de00-dcac-11eb-8c1f-c4751cbb74b5.png)

#13 로그인 기능구현에서 리뷰에 남겼던 질문에 대해 이야기가 조금 길어질것 같아서 이슈로 등록하였습니다.

**Comment by Maestro6788** [comment]
우선 결론부터 말하자면 Attribute<이름, 값>에서 이름은 세션을 식별하지 못하며 클라이언트을 식별하는 것은 세션의 ID(=JESSESIONID)라고 생각합니다.

HTTP는 비연결성이라는 특징 때문에 매번 새로운 요청에 대해 새로운 사용자라고 인식하는 단점이 있습니다. 브라우저를 종료하여도 로그인 상태를 유지할 수 있게 하기 위해 사용하는 것이 쿠키와 세션입니다. 

쿠키를 이용해 사용자 정보(아이디,비밀번호)를 서버와 클라이언트가 주고 받는다면 보안취약점이 많아 쿠키에 세션ID를 JESSIONID로 저장하여 쿠키를 전달합니다. 
 
쿠키는 JSESSIONID를 웹 브라우저(클라이언트)에 저장하고 서버가 요청할 때 JSESSIONID를 함께 보내 서버가 클라이언트를 식별할 수 있게 해줍니다. 이때 서버가 클라이언트를 식별하는 식별자는 JSESSIONID라고 생각합니다. 

또한 쿠키에는 장바구니 목록, 7일동안 게시글 보지 않기 정보등을 저장하여 활용할 수 있으며 세션의 정보는 서버에 저장되며 Attribute<이름,값>에 저장된 값(회원정보(아이디,비밀번호))을 활용하여 데이터베이스에 다시 접근하지 않더라도 사용자의 아이디와 비밀번호를 확인하고 활용이 가능하다고 이해하였습니다. 

하지만 여전히 세션의 이름은 어떤 역할을 하고 왜 대부분의 사람들이 상수로 지정하는지에 대해서는 잘 모르겠습니다.

![image](https://user-images.githubusercontent.com/83272619/124369997-0e29b780-dcad-11eb-8531-92b4e7702ea1.png)

**Comment by yusok7** [comment]
멘토님과 은수님의 좋은 comment로 저 또한 세션의 식별자는 JSessionId라고 생각합니다.
그렇다면 session attribute의 name은 어떠한 역할일까 ? 저 또한 많은 생각을 해봤습니다. 

우선 책과 블로그에서 공통적으로 말하길 **"일반적으로 하나의 브라우저에서는 세션을 공유, 즉 하나의 세션만 생성"** 한다고 합니다.
이는 session attribute의 name값이 동일한 상수값이므로 가능하다고 생각합니다.
동일한 name의 세션이 생성되면, 그 이전의 세션은 사라지기 때문입니다.

반대로 세션이 매번 생성될 때마다 name 값이 달라지면 어떻게 될까? 생각을 해봤습니다.
간단히 예시를 들면 ( 세션의 유지 시간은 30분이라고 가정 )
하나의 컴퓨터에서 A 사용자가 웹 브라우저를 사용 후 로그아웃이 없이 사용을 마칩니다.
동일한 컴퓨터에 B사용자가 30분 이내에 브라우저에 로그인을 합니다.
이렇게 되면 컴퓨터에는 생성된 세션이 2개이고, B사용자가 어떠한 요청을 보내면 
A사용자의 JsessionId, B사용자의 JsessionId 이렇게 모두 전달이 되지 않을까? 라는 생각을 했습니다.

이러한 상황을 방지하기 위해 특별한 상황이 아니고서야 session의 name은 동일한 상수로 지정하는 것이지 않을까? 라고 저는 생각해봤습니다!
