### ISSUE TITLE
필터를  원하는 메소드에만 지정하기 (URL 사용X)

### ISSUE THREAD

**Issue by Maestro6788** [f-lab-edu/FoodEats#16]
멘토님 질문이 있습니다. 

필터를 기존에 URL을 통해 지정하는 것이 아닌 AOP와 같이 원하는 메소드에 적용하고자 하였습니다.
처음 구현하고자 하였던 방법은 Custom Annotation을 만들어 AOP와 동일하게 구현하고자 하였습니다.

![image](https://user-images.githubusercontent.com/83272619/125021724-2b4bf500-e0b6-11eb-80ea-89b67c52c6f0.png)
![image](https://user-images.githubusercontent.com/83272619/125021791-474f9680-e0b6-11eb-9a43-572330237984.png)
하지만 원하는 대로 메소드에 적용하지 못하였습니다.

혹시 문제에 대해 피드백 해주실수 있나요?! 
감사합니다.

@f-lab-bright 
@yusok7

**Comment by f-lab-bright** [comment]
@Maestro6788 @yusok7 
어떤 부분에서 잘 안되셨나요??

**Comment by Maestro6788** [comment]
(사진은 필터가 아닌 인터셉터 부분입니다. 둘 다 Custom Annotation 적용이 가능하다고 생각하여 인터셉터에 먼저 진행하였습니다.)

제가 생각한 방식은 인터셉터의 preHandler 부분에 어노테이션 정보가 없다면 컨트롤러로 넘어가지 못하게 return false를 하는 방식입니다. 
![image](https://user-images.githubusercontent.com/83272619/125023609-330d9880-e0ba-11eb-8c47-b63fb0b04396.png)
어노테이션 정보는 구글링을 통해서 다음 코드 부분에서 받아 올수 있다는 블로그 글을 본적이 있습니다. 
AopAuth filter = handlerMethod.getMethod().getAnnotation(AopAuth.class);

![image](https://user-images.githubusercontent.com/83272619/125023755-7b2cbb00-e0ba-11eb-9522-6b0a38fd9849.png)
하지만 println문으로 출력결과 null만 출력되는 것을 확인하였습니다.

![image](https://user-images.githubusercontent.com/83272619/125023873-b333fe00-e0ba-11eb-99df-dfabd46218d6.png)
AopAuth가 제가 직접 만든 어노테이션이며 해당 사진은 원하는 메소드에 적용시킨 사진입니다.

**Comment by f-lab-bright** [comment]
일단 필터에서는 메소드의 매핑 정보를 바로 알 수 없기 때문에 annotation 방식을 구현하긴 어려울 것 같네요.
getMethod().getAnnotation(), getMethodAnnotation() 두 가지가 동일한 방식으로 동작할까요?
getMethodAnnotation()의 경우에는 결과가 어떤지 확인해보셨나요?

**Comment by Maestro6788** [comment]
두 가지 모두 null값이 출력되었습니다. 
인터셉터에서 어노테이션 정보를 얻어올 수 있는 방법에 대해 조금더 찾아보고 다시 구현해 보도록 하겠습니다. 

+ 필터는 어노테이션과 url 말고 메소드에 직접 적용할 수 있는 방법을 혹시 키워드로 알려주실수 있나요?

**Comment by f-lab-bright** [comment]
아뇨 필터에서는 그런 방식으로 구현하지 않습니다 보통.
인터셉터로 구현하시는 방식이 맞습니다.
우선은 저 방식대로 했을 때 정상적으로 annotation을 읽어올 수 있어야 합니다.
Annotation을 선언할 때 @Target, @Retention, @Documented 등의 값이 어떤 의미인지 확인해보셨나요?
@Retention이 CLASS로 선언된건 어떤 의미일까요?
혹은, 다른 값을 가지는 경우에는 어떤 의미일까요?

**Comment by Maestro6788** [comment]
![image](https://user-images.githubusercontent.com/83272619/125028957-d616e000-e0c3-11eb-8b3d-12e603c9b4f8.png)
![image](https://user-images.githubusercontent.com/83272619/125028988-e75fec80-e0c3-11eb-9d39-c82c7bc70f30.png)

@Retention(RetentionPolicy.RUNTIME)
retention을   Runtime으로 수정하여  정상적으로 작동하는 것을 확인하였습니다! (Annotation 기반 인터셉터 적용)

Q1) "@target, @retention, @documented 등의 값이 어떤 의미인지 확인해보셨나요?"
Q2) "@retention이 CLASS로 선언된건 어떤 의미일까요?"
Q3) "혹은, 다른 값을 가지는 경우에는 어떤 의미일까요?"

멘토님의 질문에 대해 공부하여 주말내로 답변을 할 수 있도록 하겠습니다!

**Comment by Maestro6788** [comment]
https://joinwithyou.tistory.com/76
멘토님께서 주신 질문에 대해 공부를 하였습니다. 

@Retention은 어노테이션 타입을 어디까지 보유할지, 라이프 타임을 설정하는 것이라고 생각합니다.

Retention을 **CLASS**으로 지정한다면
컴파일러가 컴파일에서는 어노테이션의 메모리를 가져가지만 실질적으로 런타임시에는 사라지게 되며
Retention을 **RUNTIME**으로 지정한다면
어노테이션 정보가 런타임 종료시까지 메모리에 살아있다고 생각합니다.
 

공부를 하며 왜 AOP에는 Retention이 CLASS으로 설정 해야 하고
인터셉터에서는 Retention이 Runtime으로 해야 하는지 동작과정에 대해 잘 이해를 못하겠습니다.

혹시 이 부분에 대해 찾아볼 이론이나 키워드에 대해 가르쳐 주실 수 있나요?

**Comment by f-lab-bright** [comment]
@Maestro6788 @yusok7 
이미 키워드는 다 알고 계시네요.
그 이상 더 자세히 설명하는 자료는 글쎄요..
지금 알고 있는 상황에서 왜 그런지 고민해보시고, 실제 코드나 런타임의 정보들을 확인해보면서 직접 이해해보시는 노력을 좀 해보시면 좋을 것 같습니다.
지금 찾아보신 정도로 이미 동작을 이해하는데 필요한 모든 배경지식은 다 준비된 상태라 생각됩니다 :)

**Comment by Maestro6788** [comment]
네! 감사합니다. 

aop랑 인터셉터 코드를 직접 돌려보면서 안에 어떤 정보가 전달이 되고 출력되는지 런타임 정보를 확인해 보면서 이해해 보도록 하겠습니다.
